### ISSUE TITLE
Empty console.log() prints line number?

### ISSUE THREAD

**Issue by aocenas** [socketsupply/union-app-studio#11]
Not sure if that is expected behaviour or not.
<img width="788" alt="screen shot 2018-01-22 at 15 37 48" src="https://user-images.githubusercontent.com/1014802/35226064-6e8fe81e-ff8a-11e7-96c9-bc1825a7c1b2.png">

**Comment by heapwolf** [comment]
oh, haha. ok we should check for an empty string.

**Comment by sunilhari** [comment]
Has submitted a PR to resolve the same.Please have a look

**Comment by sunilhari** [comment]
Can we close this issue?

**Comment by heapwolf** [comment]
@sunilhari definitely, and thanks for the contribution!
