### ISSUE TITLE
features

### ISSUE THREAD

**Issue by nusson** [socketsupply/union-app-studio#12]
- 'log()' shortcut (console.log is long for just debuging)
- ability to embed libraries
  - Would be nice to play with vuejs, rxjs, moment, lodash whatever directly in that console
  - So it would be nice to embed libraries (stored so when i kill and restart the app, i still can play with my favorites libraries)

**Comment by heapwolf** [comment]
With `log`, the only real objection i could see from people is that it would pollute the global scope.

With embedding you can already do that. Just set your working directory to a place where those modules are installed. For example, 

```bash
mkdir ~/sandbox
cd sandbox
npm install react
```

Then you can set your `Working Directory` to `~/sandbox` from the menu...

![image](https://user-images.githubusercontent.com/136109/35237999-7f5bafd0-ffac-11e7-8533-e74e2279725e.png)


Or, you can start `Scratches` it from the command line, like this...

```
/Applications/Scratches.app/Contents/MacOS/Scratches .
```

**Comment by heapwolf** [comment]
@nusson I updated the readme to reflect how to embed/use modules from npm :)

**Comment by nusson** [comment]
Thanks !!!, and I think you're right for the log
+ I'm able to set this in my sandbox ;)

**Comment by heapwolf** [comment]
🎉 awesome! ok, i'll close this for now then.
