### ISSUE TITLE
requiring npm packages

### ISSUE THREAD

**Issue by zeke** [socketsupply/union-app-studio#13]
👋 Yo!

It would be cool to be able to `require('foo')` and have it happen on the fly.

Maybe something like https://github.com/hughsk/installify would make it possible.

**Comment by zeke** [comment]
Oh I see this: https://twitter.com/0x00A/status/955157792280776705

> Also, you can now select a directory that contains node_modules you want to use. For example, `npm install preact` to a new directory, then set that as your working directory and have fun :)

And that's outlined in the readme too. 👍

**Comment by heapwolf** [comment]
Yeah, I'm +1 on a more streamlined way to do it on the fly, i'm just not 100% sure of the UX.

**Comment by zeke** [comment]
Hey when and if you're ready you should add this to [electron-apps](https://github.com/electron/electron-apps/blob/master/contributing.md) so more people will find it.

(Aside: We need to make it easier to submit apps. The process is still a bit futzy.)

**Comment by heapwolf** [comment]
Yes! Almost forgot about that. I'll add it and then maybe also add some feedback about it.
