### ISSUE TITLE
Option to clear Console and Document window.

### ISSUE THREAD

**Issue by alankey-dev** [socketsupply/union-app-studio#17]
Option to clear Console and Document window on the evaluation of the code.
Perhaps add a new option in the options menu to toggle on clearing on evaluation.

**Comment by heapwolf** [comment]
Could be a menu option?

**Comment by alankey-dev** [comment]
Yeah.  That would work.  I'm using Windows and not sure on the functionality (it could be a bug or an enhancement).

**Comment by heapwolf** [comment]
I've been just doing `Ctrl+A` and then I start typing, but this could be a great first PR for someone :)

**Comment by sunilhari** [comment]
@0x00A Shall i work on this issue ??

**Comment by sunilhari** [comment]
Technically now it is not my first PR @0x00A  :) How should the fix be.
The console and Document window should be cleared after execution of the code.Is that it.What should be the case if the 'Auto Evaluate' Option is checked ??

**Comment by heapwolf** [comment]
@sunilhari yeah go for it if you want :)

It seems like the state of the document window should be reset prior to evaluating the source text (every time). Leaving some state might unintended side effects in some cases. A menu item that reset all state and emptied all input would be great too.

**Comment by alankey-dev** [comment]
For example:
if you type: 
`document.write("Test");`
In the document window **"Test"** is written as expected.

now if you write
`document.write("Hello World!");`
the document window now consists of:
**"Test Hello World"**

Deleting the line  `document.write("Test");`
consequently, the document window now contains:
**"Test Hello World! Hello World!"**

What needs to happen is the document window needs to clear on the evaluation of the code.

**Comment by sunilhari** [comment]
Thanks for the explaintation @Bigalan09 .Have raised a PR for the same.

**Comment by sunilhari** [comment]
Kindly close this issue @0x00A
