### ISSUE TITLE
Vim keybinding support

### ISSUE THREAD

**Issue by tomarrell** [socketsupply/union-app-studio#18]
Would be awesome to be able to support basic Vim keybindings.

An alternative would be to allow manually modifying keybindings for certain actions.

**Comment by tomarrell** [comment]
It looks as though the editor library you're using supports Vim keybindings. This looks to be the case of allowing a configuration option to change between binding modes. 

https://codemirror.net/demo/vim.html

**Comment by heapwolf** [comment]
I'm a vim user, also this would be trivial to add. Perhaps an item under the `Options` menu.

**Comment by blogscot** [comment]
Please see #37

**Comment by heapwolf** [comment]
Thanks to @blogscot this is in 40661a0dddb5a8b01db3c2173f08e1ff0f513e0b!
