### ISSUE TITLE
Check for updates button

### ISSUE THREAD

**Issue by cassmtnr** [socketsupply/union-app-studio#19]
Hello, very good tool!!

I would like to collaborate including a "Check for update" button in the About scratches submenu, how should I start? I looked on the source for the about menu but didn't found it.

Thank you!

**Comment by heapwolf** [comment]
We could definitely add automatic updates. This would not require an update server since this is an open source / public project (electron-builder can check github directly for releases).

**Comment by cassmtnr** [comment]
Ok, marking as closed then 😃
