### ISSUE TITLE
scratches/index.js:5:7: 'ipc' is assigned a value but never used.

### ISSUE THREAD

**Issue by cassmtnr** [socketsupply/union-app-studio#20]
```yarn lint``` command is giving error:
	```scratches/index.js:5:7: 'ipc' is assigned a value but never used.```

And on the code there is:

```const ipc = require('electron').ipcMain``` not being used.

**Comment by heapwolf** [comment]
Good catxh @cassianomon! Fixed in ee82f22d060583bfd2948df44ac344e426c0591a. :)
