### ISSUE TITLE
Comment as last line throws error

### ISSUE THREAD

**Issue by colinhowells** [socketsupply/union-app-studio#25]
Loving this, thanks for making it. I can see it becoming really useful as I learn and try things out!

If a comment's the last line of a script, an error's thrown:

```
var something = 'yo';
console.log(something);
//this being on the last line results in `SyntaxError: Unexpected end of input`
```

using 0.0.6

**Comment by heapwolf** [comment]
Thanks for the kind words! But also thanks for the heads up, I never noticed this :)

**Comment by heapwolf** [comment]
Oh, also, the fix is in master but I will roll it into the next release after a few other fixes.
