### ISSUE TITLE
Regex syntax error?

### ISSUE THREAD

**Issue by tizmagik** [socketsupply/union-app-studio#26]
Not sure why, but I get a syntax error here:

![image](https://user-images.githubusercontent.com/244704/35476550-d7f7035c-037f-11e8-9024-35d5b72520f0.png)

```js
const extractSrc = scriptStr => {
  const SCRIPT_SRC_REGEX = /<script.*src="(.*)"><\/script>/gi;
  const [, url] = SCRIPT_SRC_REGEX.exec(scriptStr);
  return url;
};
```

**Comment by heapwolf** [comment]
I boiled it down to this.

```js
const r = /foo\/bar>/
```

A clue for a fix is that escaping fixes it...

```js
const r = /foo\\/bar>/
```

I'm guessing that since we escape the source-text, this is an escaping case I'm not accounting for. Shouldn't be too hard to fix.

**Comment by heapwolf** [comment]
Thanks for bringing up the issue by the way! I pushed a fix to master, and will include it in the next build. The following script should work now. Let me know if there are any other issues with this, feel free to reopen if needed. :)

```js
const extractSrc = scriptStr => {
  const SCRIPT_SRC_REGEX = /<script.*src="(.*)"><\/script>/gi;
  const [, url] = SCRIPT_SRC_REGEX.exec(scriptStr);
  return url;
};

console.log(extractSrc(`<script src="x"></script>`))
```

**Comment by tizmagik** [comment]
Great work! Thanks 🙏
