### ISSUE TITLE
Unable to Exit on Windows

### ISSUE THREAD

**Issue by ppseprus** [socketsupply/union-app-studio#29]
Nice project and it works pretty nice on my Mac, however, when I installed it on my work PC, I was unable to simple close the application. Not sure what else to write... : )

**Comment by heapwolf** [comment]
Thanks! Support for windows is scheduled in #7. Let's track progress over there for Windows support and I'll close this issue for now. The exiting issue has actually been fixed in the master branch already and will get into the next build.

**Comment by ppseprus** [comment]
Oh! Okay! Sorry then, my mistake! : )
