### ISSUE TITLE
Show Version Informations

### ISSUE THREAD

**Issue by ppseprus** [socketsupply/union-app-studio#30]
Would be a great **enhancement** to have the _chromium_, _node_ and _v8_ versions in the header (or somewhere else).
Easier than `console.log(process.versions);`

**Comment by heapwolf** [comment]
Agreed! This is a great idea.

**Comment by heapwolf** [comment]
Added in 5cf4ee9dd0d87b7e677def845753edbde15f44e5.

**Comment by ppseprus** [comment]
Thanks man! : )
