### ISSUE TITLE
Invoking from terminal throws a warning

### ISSUE THREAD

**Issue by bhagatparwinder** [socketsupply/union-app-studio#31]
Invoking scratches from the terminal throws a warning. Not critical but not ideal either. The warning is 

`Scratches[5276:142377] *** WARNING: Textured window <AtomNSWindow: 0x7fe4f5c7cba0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by heapwolf** [comment]
This is an upstream/electron issue but I think it is fixed in `1.8.x` (https://github.com/electron/electron/issues/11743)

**Comment by heapwolf** [comment]
Does not appear to be fixed in `1.8.x` 5cf4ee9dd0d87b7e677def845753edbde15f44e5.

**Comment by heapwolf** [comment]
An upstream fix is needed, I'll bring this to the electron repo.
