### ISSUE TITLE
Evaluate code on keyboard shortcut

### ISSUE THREAD

**Issue by rendertom** [socketsupply/union-app-studio#33]
Any chance you could add option to evaluate code on some keyboard shortcut click instead of evaluating when stop typing?
Loving the project so far!

**Comment by heapwolf** [comment]
Maybe something like cmd+enter?

**Comment by rendertom** [comment]
Yeah, that would work great.

**Comment by heapwolf** [comment]
Ok, let's add this to the next release.

**Comment by heapwolf** [comment]
@rendertom Added in 40661a0dddb5a8b01db3c2173f08e1ff0f513e0b. I did `CommandOrControl+R` (refresh like a browser?), if you get a chance, pull from master and let me know what you think :)
