### ISSUE TITLE
Regex pattern throws error

### ISSUE THREAD

**Issue by juliedavila** [socketsupply/union-app-studio#41]
The following throws an error

```js
const notHiddenFile = (filePath) => !(/(^|\/)\.[^/.]/).test(filePath)
```

The error is

`SyntaxError: Unexpected token [`

**Comment by heapwolf** [comment]
I think this is now fixed in the `master` branch. Can you pull latest and confirm? If so, we can close.

![image](https://user-images.githubusercontent.com/136109/36721224-8df835d0-1baa-11e8-83d3-cadc2e29b103.png)
