### ISSUE TITLE
Install other dependencies

### ISSUE THREAD

**Issue by CherryNerd** [socketsupply/union-app-studio#45]
Would it be possible to dynamically integrate other modules as well?
This would make it possible to add superagent for instance, to create superfast prototypes :)

**Comment by heapwolf** [comment]
This is do-able today! :)

First, (optionally) create a project...
```
mkdir ~/myproject
cd ~/myproject
npm i superagent
```

Then just set the working directory to where the `node_modules` are installed that you want to use...

![image](https://user-images.githubusercontent.com/136109/36748310-c544a2c4-1bf7-11e8-969d-b7aef889089c.png)
