### ISSUE TITLE
Automate linux and windows builds with CI

### ISSUE THREAD

**Issue by heapwolf** [socketsupply/union-app-studio#47]
It would be great if we could get build automation set up using CI. Travis-CI could handle macOS and Linux but I'm not familiar with a Windows based CI that has an open source tier.

**Comment by heapwolf** [comment]
Would fix #34

**Comment by staticfrost** [comment]
This would be great. I'll give it a look this week. I see the link task has a great idea.

**Comment by staticfrost** [comment]
@0x00A you able to say how you currently do the builds so I don't stop that bit from working whilst playing?

**Comment by heapwolf** [comment]
I was going to set up travis-ci but it's still a TODO.

**Comment by staticfrost** [comment]
So you are manually doing the builds now?

just npm build though?
