### ISSUE TITLE
Feature Dream: TypeScript Support

### ISSUE THREAD

**Issue by fbartho** [socketsupply/union-app-studio#5]
Is there any way to run this with TypeScript?

**Comment by heapwolf** [comment]
Currently looking at a way to import stuff like TypeScript & JSX without hardcoding it into the project. Ideally, you will be able to use any framework, transpiler, etc.

**Comment by heapwolf** [comment]
Open to PRs on this. A _really_ clever solution might not add more than a few lines ;)

**Comment by fbartho** [comment]
@0x00A -- That sounded like a great teaser, but did you have a specific thing in mind?

**Comment by heapwolf** [comment]
Still experimenting, I may have something that will work.

**Comment by sunilhari** [comment]
@0x00A Can we close this issue
