### ISSUE TITLE
Automatically set the libs path when opening from console 

### ISSUE THREAD

**Issue by danielo515** [socketsupply/union-app-studio#52]
Hello.

I think it may be nice if you can open scratches passing a directory to it and use that as working directory: being able to require local files, use installed  modules and that stuff. 

Regards

**Comment by heapwolf** [comment]
Hm. This could be a regression. This was working at one point. I will investigate.

**Comment by danielo515** [comment]
Hello @0x00A , I'm not saying that this is not working. I guessed that this was not possible reading the docs. If that was your intention then it probably works

**Comment by heapwolf** [comment]
👍 Ok, I will see about adding a test for this.

EDIT
And also some docs :)
