### ISSUE TITLE
Make "Save" save to the current file (0.7.0, Mac)

### ISSUE THREAD

**Issue by crcdng** [socketsupply/union-app-studio#54]
Currently `Save` asks for a filename each time. This should only happen for the first time.

`Save` should save the current buffer to the current file.
`Save as` to save with a different file name.

**Comment by heapwolf** [comment]
cc @blogscot

**Comment by blogscot** [comment]
Please see PR #55

**Comment by heapwolf** [comment]
Merged in #55
