### ISSUE TITLE
Code formatting with prettier

### ISSUE THREAD

**Issue by Haroenv** [socketsupply/union-app-studio#59]
Could be done one a certain keystroke like "cmd-s", or automatically like the output panel, but that might break the code while you're still writing it.

**Comment by heapwolf** [comment]
:+1: that would be awesome

**Comment by Haroenv** [comment]
What do you think wrt key shortcuts or automatically? I personally have the save shortcut remembered as also being the prettier one because I use format on save, but maybe another one could make sense as well. Could maybe have a button too

**Comment by heapwolf** [comment]
Good question we made the "reset" key `Command + <backtick>` and that was a bad idea because on macOS that is the key used to toggle between windows. So while we're at this we should maybe rethink that shortcut too.
