### ISSUE TITLE
Stop the execution

### ISSUE THREAD

**Issue by g-ongenae** [socketsupply/union-app-studio#60]
Hello,

Is there a way to stop the execution of the code?
Or how can I clean the cache?

I have done a terrible mistake: a simple infinite loop, and I cannot clean the code executed on start. So the app keep failing on load.

<img width="429" alt="Error: Cannot read property 'webContents'" src="https://user-images.githubusercontent.com/9453090/46353210-262b0300-c64b-11e8-997d-d46465521f88.png">
This error is only thrown when I try to quit the app or to call another method in the menu, I cannot edit the code in the editor.

---
Also, I think there's a typo here, it should be `Light`, ain't it? https://github.com/hxoht/scratches/blob/9afe7fbfec7b7e2aafd347317e13c4d0fc904b21/src/node_modules/menu/index.js#L178

**Comment by partyconfetti** [comment]
I just did the same thing and fixed it by deleting local storage files.

Try deleting this folders (resets all preferences):

**Windows:**
`C:\Users\<user>\AppData\Roaming\Scratches\Local Storage`

**Linux:**
`/home/<user>/.config/Scratches/Local Storage`

**OS X:**
`/Users/<user>/Library/Application Support/Scratches/Local Storage`
