### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by crazy4groovy** [socketsupply/union-app-studio#7]
Nice project! Reminds me of https://github.com/princejwesley/Mancy

A Windows installation file would be swell, donchathink? :)

**Comment by heapwolf** [comment]
Implementation note. A requirement for this is switching to the expected "close window" behavior. Windows apps are expected to close completely when the main window is closed (as noticed in #15)

**Comment by heapwolf** [comment]
#15 is addressed in 516f639399502c127cc7d9f52d6efb35e0258a00, but before I close this I'll run it on a windows machine. After that I'll create a new build.

**Comment by blogscot** [comment]
Please see PR #40
